// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bison.Razor.Migrations
{
    [DbContext(typeof(BisonDbContext))]
    [Migration("20261003104324_AddPosts")]
    partial class AddPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("post_id");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("author_id");

                    b.Property<long>("PubDate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pub_date");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.ToTable("post", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.Property<int>("TaxonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("taxon_id");

                    b.Property<string>("DwcTaxonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dwc_taxon_id");

                    b.Property<int?>("ParentTaxonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_taxon_id");

                    b.Property<string>("VernacularName")
                        .HasColumnType("TEXT")
                        .HasColumnName("vernacular_name");

                    b.HasKey("TaxonId");

                    b.HasIndex("ParentTaxonId");

                    b.ToTable("taxon", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("PwHash")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pw_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasBaseType("Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observation_id");

                    b.HasIndex("ObservationId");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("Observation", b =>
                {
                    b.HasBaseType("Post");

                    b.Property<int>("TaxonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("taxon_id");

                    b.HasIndex("TaxonId");

                    b.ToTable("observation", (string)null);
                });

            modelBuilder.Entity("Proposal", b =>
                {
                    b.HasBaseType("Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observation_id");

                    b.Property<int>("TaxonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("taxon_id");

                    b.HasIndex("ObservationId");

                    b.HasIndex("TaxonId");

                    b.ToTable("proposal", (string)null);
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.HasOne("User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.HasOne("Taxon", "ParentTaxon")
                        .WithMany("ChildTaxons")
                        .HasForeignKey("ParentTaxonId");

                    b.Navigation("ParentTaxon");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("Observation", "Observation")
                        .WithMany("Comments")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Post", null)
                        .WithOne()
                        .HasForeignKey("Comment", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("Observation", b =>
                {
                    b.HasOne("Post", null)
                        .WithOne()
                        .HasForeignKey("Observation", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taxon", "Taxon")
                        .WithMany("Observations")
                        .HasForeignKey("TaxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Proposal", b =>
                {
                    b.HasOne("Observation", "Observation")
                        .WithMany("Proposals")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Post", null)
                        .WithOne()
                        .HasForeignKey("Proposal", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taxon", "Taxon")
                        .WithMany("Proposals")
                        .HasForeignKey("TaxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.Navigation("ChildTaxons");

                    b.Navigation("Observations");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Observation", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
