// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bison.Razor.Migrations
{
    [DbContext(typeof(BisonDbContext))]
    [Migration("20261001130715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("comment_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<double>("TimeStamp")
                        .HasColumnType("REAL")
                        .HasColumnName("timestamp");

                    b.Property<int>("author_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("observation_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("author_id");

                    b.HasIndex("observation_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("observation_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<double>("TimeStamp")
                        .HasColumnType("REAL")
                        .HasColumnName("timestamp");

                    b.Property<int>("author_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("taxon_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("author_id");

                    b.HasIndex("taxon_id");

                    b.ToTable("observation", (string)null);
                });

            modelBuilder.Entity("Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<double>("TimeStamp")
                        .HasColumnType("REAL")
                        .HasColumnName("timestamp");

                    b.Property<int>("author_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("observation_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("taxon_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("author_id");

                    b.HasIndex("observation_id");

                    b.HasIndex("taxon_id");

                    b.ToTable("proposal", (string)null);
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.Property<int>("TaxonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VernacularName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vernacular_name");

                    b.Property<int?>("parent_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaxonId");

                    b.HasIndex("parent_id");

                    b.ToTable("taxon", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("PwHash")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pw_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("User", "Author")
                        .WithMany()
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Observation", "observation")
                        .WithMany()
                        .HasForeignKey("observation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("observation");
                });

            modelBuilder.Entity("Observation", b =>
                {
                    b.HasOne("User", "Author")
                        .WithMany()
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taxon", "Taxon")
                        .WithMany()
                        .HasForeignKey("taxon_id");

                    b.Navigation("Author");

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Proposal", b =>
                {
                    b.HasOne("User", "Author")
                        .WithMany()
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Observation", "observation")
                        .WithMany()
                        .HasForeignKey("observation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taxon", "Taxon")
                        .WithMany()
                        .HasForeignKey("taxon_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Taxon");

                    b.Navigation("observation");
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.HasOne("Taxon", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
